admin_manufacturers:
    path: /
    methods: [GET]
    defaults:
        _controller: PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:index
        _legacy_controller: AdminManufacturers

admin_manufacturers_add:
    path: /add
    methods: [GET, POST]
    defaults:
        _controller: PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:add
        _legacy_controller: AdminManufacturers

admin_manufacturers_edit:
    path: /edit/{manufacturerId}
    methods: [GET, POST]
    defaults:
        _controller: PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:edit
        _legacy_controller: AdminManufacturers
    requirements:
        manufacturerId: \d+

admin_manufacturers_view:
    path: /view/{manufacturerId}
    methods: [GET, POST]
    defaults:
        _controller: PrestaShopBundle:Admin/Sell/Catalog/Manufacturer:view
        _legacy_controller: AdminManufacturers
    requirements:
        manufacturerId: \d+
