services:
    _defaults:
        public: true

    prestashop.adapter.grid.search.factory.search_criteria_with_category_parent_id:
        class: 'PrestaShop\PrestaShop\Adapter\Grid\Search\Factory\SearchCriteriaWithCategoryParentIdFilterFactory'
        arguments:
            - '@prestashop.adapter.legacy.configuration'
            - '@prestashop.adapter.shop.context'
            - '@prestashop.adapter.feature.multistore'
            - '@prestashop.adapter.shop.context'
            - '@=service("prestashop.adapter.legacy.context").getContext().shop.id_category'

    # Action accessibility checkers
    prestashop.adapter.grid.action.checker.category_for_view_action_checker:
        class: 'PrestaShop\PrestaShop\Adapter\Grid\Action\Checker\CategoryForViewActionChecker'
        arguments:
            - '@=service("prestashop.adapter.legacy.context").getContext().language.id'

    prestashop.adapter.grid.action.checker.delete_employee_action_checker:
        class: 'PrestaShop\PrestaShop\Adapter\Grid\Action\Checker\DeleteEmployeeActionChecker'
