services:
    _defaults:
        public: true

    prestashop.adapter.manufacturer.manager:
        class: 'PrestaShop\PrestaShop\Adapter\Manufacturer\ManufacturerManager'
        arguments:
            - '@prestashop.adapter.manufacturer.image_uploader'

    prestashop.adapter.manufacturer.product_provider:
        class: 'PrestaShop\PrestaShop\Adapter\Manufacturer\ManufacturerProductProvider'

    prestashop.adapter.manufacturer.thumbnail_generator:
        class: 'PrestaShop\PrestaShop\Adapter\Manufacturer\ManufacturerThumbnailGenerator'

    prestashop.adapter.manufacturer.image_uploader:
        class: 'PrestaShop\PrestaShop\Adapter\Manufacturer\ManufacturerImageUploader'
        arguments:
            - '@prestashop.adapter.legacy.configuration'
