services:
    _defaults:
        public: true

    prestashop.adapter.manufacturer.manager:
        class: 'PrestaShop\PrestaShop\Adapter\Manufacturer\ManufacturerManager'
        arguments:
            - '@prestashop.adapter.manufacturer.image_uploader'
