imports:
    - { resource: services/bundle/*.yml }
    - { resource: services/core/*.yml }
    - { resource: services/adapter/*.yml }
    - { resource: services/alias.yml }

services:
    _defaults:
        public: true

    prestashop.adapter.manufacturer.image_uploader:
        class: 'PrestaShop\PrestaShop\Adapter\Manufacturer\ManufacturerImageUploader'
        arguments:
            - '@prestashop.adapter.legacy.configuration'
